debug: false

logging.level:
  io.pivotal.dmfrey: DEBUG

server:
  port: ${PORT:9081}

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

---
spring:
  profiles: event-store

  cloud:
    stream:
      bindings:
        input:
          binder: rabbit
          destination: board-event-notifications
          contentType: application/json
          consumer:
            headerMode: raw # Outbound data has no embedded headers

---
spring:
  profiles: kafka

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: board-events
          group: query-board-events-group
          consumer:
            useNativeDecoding: true
            headerMode: raw
      kafka:
        streams:
          binder:
            brokers: localhost
            zkNodes: localhost

logger.level:
  org.apache.kafka: DEBUG
  org.apache.kafka.clients: ERROR